version: '3.9'

services:
  turbo:
    tty: true
    user: $UID:$GID
    build:
      dockerfile: Dockerfile
      args:
        UID: $UID
        GID: $GID
        UNAME: $UNAME
    ports:
      - "3100:3000"
    volumes:
      - .:/app

  db:
    image: postgres:16.3
    ports:
      - "5532:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./db-data:/var/lib/postgresql/data
